development:
  domain: localhost:3000
  wkhtmltopdf: /Users/mephux/.rvm/gems/ruby-1.9.2-p0/bin/wkhtmltopdf
  mailer_sender: 'snorby@snorby.org'
  rules: 
    - "/Users/mephux/.snort/rules"
    - "/Users/mephux/.snort/so_rules"
  authentication_mode: database
  cas_config:
    base_url: https://auth.server.com.br/
    login_url: https://auth.server.com.br/login?domain=server
    logout_url: https://auth.server.com.br/logout?domain=server

test:
  domain: localhost:3000
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf
  mailer_sender: 'snorby@snorby.org'
  authentication_mode: database

# Change the production configuration 
# for your environment.
production:
  domain: 'demo.snorby.org'
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf
  mailer_sender: 'snorby@snorby.org'
  rules:
    - ""
  authentication_mode: database
